import type { DashboardMock } from "@/lib/dashboard/types";

export const dashboardMock: DashboardMock = {
  student: {
    name: "Tahsan Khan",
    email: "tahsan@gmail.com",
    initials: "TK",
  },
  examDate: "29 Jan, 2025",
  stats: [
    {
      id: "complete",
      title: "Grade progress",
      value: "87%",
      delta: "+4.56%",
      deltaPositive: true,
      variant: "donut",
      donutPercent: 87,
    },
    {
      id: "active-exams",
      title: "Active exams",
      value: "12",
      delta: "+2.1%",
      deltaPositive: true,
      variant: "bars",
      barValues: [40, 65, 45, 80, 55, 70, 90, 60, 75, 85],
    },
    {
      id: "questions",
      title: "Questions practiced",
      value: "536",
      delta: "+6.35%",
      deltaPositive: true,
      variant: "line",
      lineValues: [20, 35, 28, 45, 38, 52, 48, 60, 55, 68, 62, 70],
    },
  ],
  examsTakenSeries: [
    { month: "Jan", exams: 120, takers: 95 },
    { month: "Feb", exams: 140, takers: 110 },
    { month: "Mar", exams: 100, takers: 85 },
    { month: "Apr", exams: 160, takers: 130 },
    { month: "May", exams: 180, takers: 145 },
    { month: "Jun", exams: 150, takers: 120 },
    { month: "Jul", exams: 200, takers: 165 },
    { month: "Aug", exams: 170, takers: 140 },
    { month: "Sep", exams: 190, takers: 155 },
    { month: "Oct", exams: 210, takers: 175 },
    { month: "Nov", exams: 195, takers: 160 },
    { month: "Dec", exams: 220, takers: 185 },
  ],
  subjectResults: [
    {
      subject: "Mathematics",
      segments: [
        { key: "easy", label: "Easy", value: 35 },
        { key: "medium", label: "Medium", value: 28 },
        { key: "hard", label: "Hard", value: 22 },
        { key: "missed", label: "Missed", value: 15 },
      ],
    },
    {
      subject: "English",
      segments: [
        { key: "easy", label: "Easy", value: 42 },
        { key: "medium", label: "Medium", value: 30 },
        { key: "hard", label: "Hard", value: 18 },
        { key: "missed", label: "Missed", value: 10 },
      ],
    },
    {
      subject: "Science",
      segments: [
        { key: "easy", label: "Easy", value: 30 },
        { key: "medium", label: "Medium", value: 32 },
        { key: "hard", label: "Hard", value: 25 },
        { key: "missed", label: "Missed", value: 13 },
      ],
    },
    {
      subject: "Economics",
      segments: [
        { key: "easy", label: "Easy", value: 38 },
        { key: "medium", label: "Medium", value: 26 },
        { key: "hard", label: "Hard", value: 20 },
        { key: "missed", label: "Missed", value: 16 },
      ],
    },
  ],
  recentResults: [
    {
      id: "1",
      name: "Tahsan Khan",
      subject: "Mathematics",
      totalScore: 87.5,
      reasoning: 72,
      time: "45 min",
      analysis: [40, 55, 70, 85, 60],
      startDate: "29 Jan, 2025",
      genericScore: 82,
    },
    {
      id: "2",
      name: "Tahsan Khan",
      subject: "English",
      totalScore: 76.2,
      reasoning: 68,
      time: "38 min",
      analysis: [50, 45, 65, 70, 55],
      startDate: "28 Jan, 2025",
      genericScore: 74,
    },
    {
      id: "3",
      name: "Tahsan Khan",
      subject: "Science",
      totalScore: 91.0,
      reasoning: 85,
      time: "52 min",
      analysis: [60, 70, 80, 90, 75],
      startDate: "27 Jan, 2025",
      genericScore: 88,
    },
    {
      id: "4",
      name: "Tahsan Khan",
      subject: "Economics",
      totalScore: 64.8,
      reasoning: 58,
      time: "41 min",
      analysis: [35, 40, 50, 45, 55],
      startDate: "26 Jan, 2025",
      genericScore: 61,
    },
  ],
};
